### ISSUE TITLE
Tasks Tracker

### ISSUE THREAD

**Issue by itaditya** [itaditya/friendly-ui#1]
- [x] Change status bar color to match background
- [x] Implement React version
- [x] Search in React version
- [x] Animations in React version
- [x] People no selected content
- [x] React homepage with cross links
- [x] Loading text center aligned with icon
- [x] disabled animation for reduced motion media query
- [x] accessible buttons
- [x] readme
